FROM mysql:9.0.1-oraclelinux9

WORKDIR /docker-entrypoint-initdb.d
COPY ./init.sql .

ENV MYSQL_DATABASE=${WEIGHT_DATABASE}
ENV MYSQL_ROOT_PASSWORD=${WEIGHT_ROOT_PASSWORD}

EXPOSE 3306
VOLUME [ "/mysql_data" ]